from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path("login", views.user_login, name="login"),
    path("register", views.register, name="register"),
    path("logout", views.user_logout, name="logout"),
    path("product/<slug>", views.productDetail, name="product-detail"),
    path("product/<slug>/chkstock", views.checkSpecsStock, name="checkSpecsStock"),
    path("category/<slug>", views.categoryPage, name="category-page"),
    path("cart", views.cart_detail, name="cart-detail"),
    path("cart/add",views.add_to_cart, name="add-to-cart"),
    path("cart/rmv",views.remove_from_cart, name="remove-from-cart"),
    path("cart/upd",views.update_cart, name="update-cart"),
    path("cart/clr",views.clear_cart, name="delete-cart"),
    path("cart/buyagain", views.orderBuyAgain, name="order-item-buy-again"),
    path("profile", views.user_profile, name="user-profile"),
    path("profile/favs", views.user_favs, name="user-favs"),
    path("profile/favs/add", views.user_add_fav, name="user-add-fav"),
    path("profile/favs/rmv", views.user_remove_fav, name="user-remove-fav"),
    path("profile/address", views.user_address, name="user-address"),
    path("profile/address/rmv", views.user_address_remove, name="user-address-rmv"),
    path("profile/orders", views.user_orders, name="user-orders"),
    path("profile/order/<ordNo>", views.user_order_detail, name="user-order-detail"),
    path("profile/order/<ordNo>/refund", views.orderRefundItem, name="user-order-refund"),
    path("orderitem/addrating", views.orderAddRating, name="add-product-rating"),
    path("success", views.orderSuccess, name="order-success"),
    path("checkout", views.checkout, name="checkout"),
    path("search", views.search, name="search"),
    path("satici", views.satici, name="vendorSatici"),
    path("satici/login", views.vendorLogin, name="vendorLogin"),
    path("satici/register", views.vendorRegister, name="vendorRegister"),
    path("satici/logout", views.vendor_logout, name="vendorLogout"),
    path("satici/panel", views.vendorPanel, name="vendorPanel"),
    path("satici/panel/stats/sell", views.getVendorSellStats, name="getVendorSellStats"),
    path("satici/panel/stats/inc", views.getVendorIncomeStats, name="getVendorIncomeStats"),
    path("satici/profile", views.vendorProfile, name="vendorProfile"),
    path("satici/product/list", views.vendorProductList, name="vendorProductList"),
    path("satici/product/list/download", views.vendorProductListExcel, name="vendorProductListExcel"),
    path("satici/product/edit/<int:ind>", views.vendorEditProduct, name="vendorEditProduct"),
    path("satici/product/add", views.vendorAddProduct, name="vendorAddProduct"),
    path("satici/product/sell", views.vendorSellProduct, name="vendorSellProduct"),
    path("satici/product/sell/search/", views.vendorSellSearch, name="vendorSellSearch"),
    path("satici/product/stock/<int:ind>", views.vendorGetStock, name="vendorGetStock"),
    path("satici/product/stock/update", views.vendorUpdateStock, name="vendorUpdateStock"),
    path("satici/orders", views.vendorOrders, name="vendorOrders"),
    path("satici/order/<int:ordNo>", views.vendorOrderDetail, name="vendorOrderDetail"),
    path("satici/order/<int:ordNo>/rmv", views.vendorOrderItemCancel, name="vendorOrderItemCancel"),
    path("satici/order/<int:ordNo>/prp", views.vendorOrderItemChPrepared, name="vendorOrderItemPrepared"),
    path("satici/order/<int:ordNo>/cargo", views.vendorOrderItemCargo, name="vendorOrderItemCargo"),
    path("satici/pay", views.vendorWallet, name="vendorWallet"),
]

handler404 = views.handler404
